### ISSUE TITLE
Likeable contract problem

### ISSUE THREAD

**Issue by lukadriel7** [rennokki/befriended#38]
the likeable contract for models return always false when checking 
if (! $model instanceof Likeable && ! $model instanceof Liking)
in CanLike.php isLiking() function.

**Comment by rennokki** [comment]
It seems like it brings problems with that after this specific PR: https://github.com/rennokki/befriended/pull/35

Someone noticed https://github.com/rennokki/befriended/pull/29 and i did the same with the other two (Block & Like) and it seems like they are broken, but the follow contract not.

I'm looking forward to fix this.

**Comment by rennokki** [comment]
@lukadriel7, did you use the contract and the trait specified in the documentation?
