### ISSUE TITLE
Is there any way to detect if 2 users follow eachother?

### ISSUE THREAD

**Issue by danilogkir** [rennokki/befriended#39]
Hello, as i want to include a "message" feature for the people that follows back each other i wanted to know how to detect if they actually follow each other to enable this feature for both of this users.

Thanks

**Comment by danilogkir** [comment]
solved with: 
```
@if(Auth::user()->follows($user) && $user->follows(Auth::user()))
    <a href="/message/{{ $user->username }}" class="be-ava-right btn btn-share color-4 size-2 hover-7"><i class="fa fa-commenting-o" style="margin-left: -8px;"></i>Message</a>
@endif

**Comment by rennokki** [comment]
Hey @danilogkir,

For this, I might implement a custom function for easier usage for this specific case.

I'm looking into it in a few hours 😄
