### ISSUE TITLE
Vendor Publish Errors

### ISSUE THREAD

**Issue by josteph** [rennokki/befriended#5]
Hello, I tried `php artisan vendor:publish` and I got an error like:

`Can't locate path: </Users/agus/Sites/careerkuweb/vendor/rennokki/befriended/src/../database/migrations/2018_07_14_183253_followers.php>`

It's supposed to be `_followers.php` not `_befriended.php` in `src/database/migrations` folder.

Change README:
From `use Rennokki\Befriended\Traits\Following as FollowingTrait;`
To `use Rennokki\Befriended\Traits\Follow as FollowingTrait;`

**Comment by rennokki** [comment]
Hey @josteph,
I have checked out the issue and i had some typos in it. Fixed in https://github.com/rennokki/befriended/pull/7

**Comment by rennokki** [comment]
@josteph 
Sorry, i forgot to thank you for this observation.

I also recommend you to use ^1.1.0 since it separates migration files for better customizability and it implements the 'Like' feature.
