### ISSUE TITLE
Minor versions shouldn't make incompatible API changes

### ISSUE THREAD

**Issue by ScSherifTarek** [rennokki/befriended#63]
Hello, Thanks for the great package.

In the readme file, you mentioned moving from a minor version to another cause changing traits used which we can say are incompatible API changes that shouldn't be done in a minor version changing please check [semantic versioning](https://semver.org/).

**Comment by joveice** [comment]
@ScSherifTarek What changes are you referring to?

**Comment by ScSherifTarek** [comment]
@joveice Switching from 1.1.x to 1.2.x requires replacing some traits with another.

**Comment by joveice** [comment]
@ScSherifTarek You have a point there.

**Comment by ScSherifTarek** [comment]
@joveice Just to know for future releases :smile:

**Comment by rennokki** [comment]
Back then, very few people installed it and i made the change way before people were able to use it in production. But yes, breaking changes require new major. 😅

**Comment by ScSherifTarek** [comment]
Now no need for this issue
